# fly.toml app configuration file generated for pds-frontpage on 2025-10-05T21:33:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pds-frontpage'
primary_region = 'lhr'

[build]

[env]
LOG_ENABLED = 'true'
PDS_BSKY_APP_VIEW_DID = 'did:web:api.bsky.app'
PDS_BSKY_APP_VIEW_URL = 'https://api.bsky.app'
PDS_CRAWLERS = 'https://bsky.network'
PDS_DATA_DIRECTORY = '/pds'
PDS_DID_PLC_URL = 'https://plc.directory'
PDS_HOSTNAME = 'pds.unravel.fyi'
PDS_REPORT_SERVICE_DID = 'did:plc:ar7c4by46qjdydhdevvrndac'
PDS_REPORT_SERVICE_URL = 'https://mod.bsky.app'

PDS_BLOB_UPLOAD_LIMIT = "52428800"
# If you want to store blobs to disk, uncocomment the following lines and remove the S3-related lines
# PDS_BLOBSTORE_DISK_LOCATION = "/pds/blocks"
PDS_BLOBSTORE_S3_BUCKET = 'pds-blobs'
PDS_BLOBSTORE_S3_REGION = 'auto'

PDS_EMAIL_FROM_ADDRESS = "noreply@pds.unravel.fyi"

[[mounts]]
source = 'pds_data'
destination = '/pds'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
max_machines_running = 1
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
